name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

env:
  aws-region: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Package function
      run: |
        cd $(pwd)
        zip -r updateCryptoPricesInNotion.zip venv/lib/python3.8/site-packages
        zip -g updateCryptoPricesInNotion.zip lambda_function.py

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.aws-region }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name updateCryptoPricesInNotion --zip-file fileb://updateCryptoPricesInNotion.zip
