name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Package function
      run: |
        cd $(pwd)
        zip -r updateCryptoPricesInNotion.zip .

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-cli-action@v1
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: update-function-code --function-name updateCryptoPricesInNotion --zip-file fileb://updateCryptoPricesInNotion.zip
